apiVersion: apps/v1
kind: Deployment
metadata:
  name: ath_app
  labels:
    app: ath_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ath_app
  template:
    metadata:
      labels:
        app: ath_app
    spec:
      containers:
        - name: ath_app
          image: ghcr.io/agthuhein/ath_app:23435361362-6fc9913
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '250m'
