name: CI Pipeline Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  security-events: write
  packages: write
  contents: read

jobs:
  ci-pipeline-job:
    uses: agthuhein/reusable-workflows/.github/workflows/ci-pipeline.yml@main
    with:
      run_codeql: false
      run_sonarqube: false
      run_build: true
      run_ghcr_publish: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-wth-kubectl:
    needs: ci-pipeline-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Create Kubernetes cluster
        uses: helm/kind-action@v1

      - name: Verify cluster
        run: kubectl get nodes

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update image in deployment YAML
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          IMAGE="ghcr.io/agthuhein/athapp:${IMAGE_TAGS}"
          echo "Using image: $IMAGE"
          yq e ".spec.template.spec.containers[0].image = strenv(IMAGE)" -i manifests/deployment.yaml
          cat manifests/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl apply -f manifests/service.yaml
          echo "Waiting 10s for pods to start..."
          sleep 10
          kubectl get pods -o wide
          kubectl get svc
